import type { AppLanguage } from "./i18n";
import type { ClueId, EndingReconstruction } from "./narrative-types";

export const CLUE_KEYWORDS: Record<ClueId, string> = {
  F1: "交流",
  F2: "纪念币",
  F3: "织机",
  F4: "青瓷",
  F5: "规则",
  F6: "马车",
  F7: "书法",
  F8: "钥匙",
  F10: "捐赠",
  F11: "双展品",
  F12: "成人礼",
  F13: "乡愁",
  F14: "谐音",
  F15: "墨色",
  F16: "庆辞",
  F17: "温度",
  F18: "源头",
  F19: "翻译",
  F20: "国际化",
  F21: "乡愁",
  F22: "双视角",
  F23: "留言墙",
  F24: "共鸣",
  F25: "对话",
};

export const CLUE_KEYWORDS_EN: Record<ClueId, string> = {
  F1: "Exchange",
  F2: "Coin",
  F3: "Loom",
  F4: "Celadon",
  F5: "Rules",
  F6: "Chariot",
  F7: "Calligraphy",
  F8: "Key",
  F10: "Donation",
  F11: "Two Objects",
  F12: "Rite of Passage",
  F13: "Homesickness",
  F14: "Homophone",
  F15: "Ink",
  F16: "Celebration",
  F17: "Warmth",
  F18: "Origins",
  F19: "Translation",
  F20: "Internationalisation",
  F21: "Homesickness",
  F22: "Two Perspectives",
  F23: "Message Wall",
  F24: "Resonance",
  F25: "Dialogue",
};

export const STORY_RECONSTRUCTIONS: Record<string, EndingReconstruction> = {
  "p1-forgotten-and-missed": {
    storyId: "p1-forgotten-and-missed",
    sentencePrefix: "被暂时忽视的",
    sentenceSuffix: "，后来重新连回两校最初的交流。",
    correctOption: "捐赠",
    distractorOption: "马车",
  },
  "p1-gift-timeline": {
    storyId: "p1-gift-timeline",
    sentencePrefix: "这条礼物时间线里，纪念币像一场跨校的",
    sentenceSuffix: "。",
    correctOption: "成人礼",
    distractorOption: "青瓷",
  },
  "p1-stories-behind-donations": {
    storyId: "p1-stories-behind-donations",
    sentencePrefix: "从被搁置的捐赠到跨文化的纪念币，这段校史终于被重新写成",
    sentenceSuffix: "。",
    correctOption: "友谊",
    distractorOption: "战车",
  },
  "p1-key-and-boat": {
    storyId: "p1-key-and-boat",
    sentencePrefix: "打不开锁的钥匙，反而把远行的想象连回校园的",
    sentenceSuffix: "。",
    correctOption: "成长",
    distractorOption: "谐音",
  },
  "p2-homophones-and-coins": {
    storyId: "p2-homophones-and-coins",
    sentencePrefix: "青瓷象最难翻译的地方，不在器物本身，而在词语背后的",
    sentenceSuffix: "。",
    correctOption: "寓意",
    distractorOption: "支撑",
  },
  "p2-warmth-of-handwriting": {
    storyId: "p2-warmth-of-handwriting",
    sentencePrefix: "读不懂字也没关系，书法先通过",
    sentenceSuffix: "让人感到情绪。",
    correctOption: "墨色",
    distractorOption: "钥匙",
  },
  "p2-depth-of-translation": {
    storyId: "p2-depth-of-translation",
    sentencePrefix: "真正的跨文化",
    sentenceSuffix: "，不只是换词，还要理解词语里的文化缝隙。",
    correctOption: "翻译",
    distractorOption: "马车",
  },
  "p3-homesickness-and-aesthetics": {
    storyId: "p3-homesickness-and-aesthetics",
    sentencePrefix: "船模把这条记者线最终拉向异乡人的",
    sentenceSuffix: "。",
    correctOption: "乡愁",
    distractorOption: "规则",
  },
  "p3-rules-and-change": {
    storyId: "p3-rules-and-change",
    sentencePrefix: "真正的国际化，不是消灭差异，而是在共同的",
    sentenceSuffix: "下容纳差异。",
    correctOption: "规则",
    distractorOption: "乡愁",
  },
  "p3-silent-support-and-genuine-longing": {
    storyId: "p3-silent-support-and-genuine-longing",
    sentencePrefix: "织锦最打动人的，不只是图案，而是它把我们带回",
    sentenceSuffix: "的根源。",
    correctOption: "最初",
    distractorOption: "后来",
  },
  "p3-human-voices": {
    storyId: "p3-human-voices",
    sentencePrefix: "这组采访真正收集到的，不只是展品信息，而是围绕",
    sentenceSuffix: "的多重回答。",
    correctOption: "国际化",
    distractorOption: "留言墙",
  },
  "p4-intern-complete-record": {
    storyId: "p4-intern-complete-record",
    sentencePrefix: "教育性展览先需要可参与的",
    sentenceSuffix: "，观众才会慢慢留下自己的回应。",
    correctOption: "留言墙",
    distractorOption: "马车",
  },
  "p4-message-wall-and-chess": {
    storyId: "p4-message-wall-and-chess",
    sentencePrefix: "当棋子被轻轻移动，原本静止的规则就被转化成了",
    sentenceSuffix: "。",
    correctOption: "对话",
    distractorOption: "乡愁",
  },
  "p4-quietness-and-touch": {
    storyId: "p4-quietness-and-touch",
    sentencePrefix: "青瓷之所以让人停步，是因为它先制造了共同的",
    sentenceSuffix: "。",
    correctOption: "共鸣",
    distractorOption: "成人礼",
  },
};

export const STORY_RECONSTRUCTIONS_EN: Record<string, EndingReconstruction> = {
  "p1-forgotten-and-missed": {
    storyId: "p1-forgotten-and-missed",
    sentencePrefix: "The once-overlooked",
    sentenceSuffix: "eventually led both universities back to their earliest exchange.",
    correctOption: "donation",
    distractorOption: "chariot",
  },
  "p1-gift-timeline": {
    storyId: "p1-gift-timeline",
    sentencePrefix: "On this gift timeline, the commemorative coin feels like a shared",
    sentenceSuffix: ".",
    correctOption: "rite of passage",
    distractorOption: "celadon",
  },
  "p1-stories-behind-donations": {
    storyId: "p1-stories-behind-donations",
    sentencePrefix: "From a shelved donation to a cross-cultural coin, this chapter of campus history becomes",
    sentenceSuffix: ".",
    correctOption: "friendship",
    distractorOption: "chariot",
  },
  "p1-key-and-boat": {
    storyId: "p1-key-and-boat",
    sentencePrefix: "A key that opens nothing still ties the dream of departure back to campus",
    sentenceSuffix: ".",
    correctOption: "growth",
    distractorOption: "wordplay",
  },
  "p2-homophones-and-coins": {
    storyId: "p2-homophones-and-coins",
    sentencePrefix: "What makes the celadon elephant hard to translate is the cultural",
    sentenceSuffix: "behind the word.",
    correctOption: "meaning",
    distractorOption: "support",
  },
  "p2-warmth-of-handwriting": {
    storyId: "p2-warmth-of-handwriting",
    sentencePrefix: "Even when the words are unclear, the calligraphy still speaks through its",
    sentenceSuffix: ".",
    correctOption: "ink",
    distractorOption: "key",
  },
  "p2-depth-of-translation": {
    storyId: "p2-depth-of-translation",
    sentencePrefix: "Real cross-cultural",
    sentenceSuffix: "means more than swapping words. It means reading the culture inside them.",
    correctOption: "translation",
    distractorOption: "chariot",
  },
  "p3-homesickness-and-aesthetics": {
    storyId: "p3-homesickness-and-aesthetics",
    sentencePrefix: "In the end, the boat model pulls this story back toward",
    sentenceSuffix: ".",
    correctOption: "homesickness",
    distractorOption: "rules",
  },
  "p3-rules-and-change": {
    storyId: "p3-rules-and-change",
    sentencePrefix: "Real internationalisation does not erase difference. It makes room for it within shared",
    sentenceSuffix: ".",
    correctOption: "rules",
    distractorOption: "homesickness",
  },
  "p3-silent-support-and-genuine-longing": {
    storyId: "p3-silent-support-and-genuine-longing",
    sentencePrefix: "What makes the textile moving is not just its pattern, but how it takes us back to the",
    sentenceSuffix: "of it all.",
    correctOption: "origin",
    distractorOption: "aftermath",
  },
  "p3-human-voices": {
    storyId: "p3-human-voices",
    sentencePrefix: "These interviews gathered more than exhibit facts. They gathered many answers around",
    sentenceSuffix: ".",
    correctOption: "internationalisation",
    distractorOption: "message wall",
  },
  "p4-intern-complete-record": {
    storyId: "p4-intern-complete-record",
    sentencePrefix: "An educational exhibition first needs a space where people can take",
    sentenceSuffix: ", before they begin leaving responses.",
    correctOption: "part",
    distractorOption: "chariot",
  },
  "p4-message-wall-and-chess": {
    storyId: "p4-message-wall-and-chess",
    sentencePrefix: "When a chess piece shifts, a static set of rules becomes",
    sentenceSuffix: ".",
    correctOption: "dialogue",
    distractorOption: "homesickness",
  },
  "p4-quietness-and-touch": {
    storyId: "p4-quietness-and-touch",
    sentencePrefix: "The celadon elephant makes people pause because it first creates shared",
    sentenceSuffix: ".",
    correctOption: "resonance",
    distractorOption: "rite of passage",
  },
};

export function getClueKeywordCopy(clueId: ClueId, language: AppLanguage) {
  return language === "en" ? CLUE_KEYWORDS_EN[clueId] : CLUE_KEYWORDS[clueId];
}

export function getStoryReconstructionCopy(storyId: string, language: AppLanguage) {
  return language === "en" ? STORY_RECONSTRUCTIONS_EN[storyId] : STORY_RECONSTRUCTIONS[storyId];
}
